## Importer

In [66]:
import pandas as pd
import numpy as np
import time

## Importera data

In [67]:
base_path = "../../../ml/Datasets/combient_medlemsanalys/data/"

In [68]:
# Importera data m.h.a. Pandas:

fds_df = pd.read_csv(base_path + "1_fds_ce-2019-12-11_medlem_skogsägare.csv", sep = ",", dtype = {'Intressentnummer': 'str'})

sir_df = pd.read_csv(base_path + "2_enskildIntressent_sir-test.csv", sep = ",", dtype = {'personnummer': 'str', 'skogsleverantörsnummer': 'str'})

stubin_df = pd.read_csv(base_path + "3_avv_test_stubin.csv", sep = ";", decimal = ',', dtype = {'Timmer': np.float64, 'Massaved': np.float64})

sks_df = pd.read_csv(base_path + "4_sks_fast_med_avverkn_ett_datum.csv", sep = ";", decimal=',')#, dtype = {'AVV_AREAL': np.float64})#, 'SKOGSAREAL': np.float64})

In [69]:
fds_df.head(1)

,UUID-Fastighet,Andel,Intressent-namn,Andel Täljare,Andel Nämnare,Intressentnummer,Intressentkategori
0,{909a6a66-5ffb-90ec-e040-ed8f66444c3f},1/1,Martin Niklasson,1,1,197403304954,Skogsbrukare

In [70]:
# Ta bort {}-tecknen från fds-UUID.
# Kan detta göra snyggare?

fds_df['UUID-Fastighet'] = fds_df['UUID-Fastighet'].str.replace('{','')
fds_df['UUID-Fastighet'] = fds_df['UUID-Fastighet'].str.replace('}','')

### Ta bort och rensa n/a-värden från varje df:

In [71]:
sir_df.isna().sum()

personnummer                0
skogsleverantörsnummer      0
Vo                        219
andel_täljare              22
andel_nämnare               0
Namn                        0
dtype: int64

In [72]:
fds_df.isna().sum()

UUID-Fastighet        0
Andel                 0
Intressent-namn       1
Andel Täljare         0
Andel Nämnare         0
Intressentnummer      0
Intressentkategori    0
dtype: int64

In [73]:
stubin_df.isna().sum()

Levnr                0
Ursprung             0
Uppdrag              0
Timmer               0
Massaved             0
Ovrigt               0
KontraktsDatum       0
SistaMatdatum        0
SlutredovisnDatum    0
dtype: int64

In [74]:
sks_df.isna().sum()

UUID           0
AVVDATUM       0
FNR            0
KOMMUNNAMN     0
FASTIGHET      0
DISTRKOD       0
DISTRNAMN      0
DSBONR        59
DSBONAMN      59
AVV_AREAL      0
SKOGSAREAL     0
dtype: int64

In [75]:
fds_df.dropna(inplace = True)
sir_df.dropna(inplace = True)
stubin_df.dropna(inplace = True)
sks_df.dropna(inplace = True)

In [76]:
fds_df.head(2)

,UUID-Fastighet,Andel,Intressent-namn,Andel Täljare,Andel Nämnare,Intressentnummer,Intressentkategori
0,909a6a66-5ffb-90ec-e040-ed8f66444c3f,1/1,Martin Niklasson,1,1,197403304954,Skogsbrukare
1,909a6a69-3c60-90ec-e040-ed8f66444c3f,1/4,Monica Willnerth,1,4,195205180028,Skogsbrukare

In [77]:
type(fds_df['Intressentnummer'].iloc[0])

str

In [78]:
type(sir_df['personnummer'].iloc[0])

str

In [14]:
sir_df.head(2)

,personnummer,skogsleverantörsnummer,Vo,andel_täljare,andel_nämnare,Namn
0,194907162533,7684,989,1,1,Andreasson Mats Tommy
1,195607122560,9113,982,1,1,Svensson Suzanne

In [15]:
stubin_df.head(2)

,Levnr,Ursprung,Uppdrag,Timmer,Massaved,Ovrigt,KontraktsDatum,SistaMatdatum,SlutredovisnDatum
0,112780,5,D,165.46,235.59,14.74,2019-08-02 00:00:00.000,2019-10-04 00:00:00.000,2019-10-23 00:00:00.000
1,118150,9,D,0.00,28.33,0.00,2019-08-02 00:00:00.000,2019-10-06 00:00:00.000,2019-10-09 00:00:00.000

In [16]:
sks_df.head(2)

,UUID,AVVDATUM,FNR,KOMMUNNAMN,FASTIGHET,DISTRKOD,DISTRNAMN,DSBONR,DSBONAMN,AVV_AREAL,SKOGSAREAL
0,909a6a6e-db1e-90ec-e040-ed8f66444c3f,2016-06-14,140774403,ÅMÅL,TOPPERUD 1:6,110033,Tösse-Tydje,9871.0,Bohus-Dal,188775.0,2885373.0
1,909a6a58-24b5-90ec-e040-ed8f66444c3f,2016-05-12,100071384,RONNEBY,NORRA SIGGAMÅLA 1:4,102031,Backaryd,9631.0,Mitt-Blekinge,44027.4,428942.5

In [17]:
fds_df.columns

Index(['UUID-Fastighet', 'Andel', 'Intressent-namn', 'Andel Täljare',
       'Andel Nämnare', 'Intressentnummer', 'Intressentkategori'],
      dtype='object')

In [18]:
sir_df.columns

Index(['personnummer', 'skogsleverantörsnummer', 'Vo', 'andel_täljare',
       'andel_nämnare', 'Namn'],
      dtype='object')

In [19]:
stubin_df.columns

Index(['Levnr', 'Ursprung', 'Uppdrag', 'Timmer', 'Massaved', 'Ovrigt',
       'KontraktsDatum', 'SistaMatdatum', 'SlutredovisnDatum'],
      dtype='object')

In [20]:
sks_df.columns

Index(['UUID', 'AVVDATUM', 'FNR', 'KOMMUNNAMN', 'FASTIGHET', 'DISTRKOD',
       'DISTRNAMN', 'DSBONR', 'DSBONAMN', 'AVV_AREAL', 'SKOGSAREAL'],
      dtype='object')

## Data exploration

In [21]:
# Hur många "Skogsbrukare" har vi?

num_sb = fds_df[fds_df['Intressentkategori'] == 'Skogsbrukare'].count()[0]
print(f'{num_sb:,}') # 1000-avgränsat

139,855

In [22]:
# Hur stor andel av alla är medlemmar?
num_members = fds_df[fds_df['Intressentkategori'] == 'Medlem'].count()[0]
frac_memb = num_members / num_sb

print(f'Andelen medlemmar i underlaget är {100*frac_memb:.1f} %.')

Andelen medlemmar i underlaget är 66.0 %.

## Hjälpfunktioner

In [23]:
# En fastighet (UUID) kan ägas av flera personer.
# Därför sparas varje ägares personnummer i en lista.

def get_persnr_from_uuid(uuid):
    
    # uuid_mask = fds_df['UUID-Fastighet'] == uuid
    # person_nummer = fds_df[uuid_mask]['Intressentnummer']
    # ovan i ett svep för att inte få en varning
    # se längre ner...
    
    pnr = fds_df[fds_df['UUID-Fastighet'] == uuid]['Intressentnummer']
    
    person_nummer = []
    
    for i in pnr:
        person_nummer.append(i)
        
    return person_nummer

In [24]:
# Funktion som från ett givet 
# personnummer i fds-df returnerar 
# ett UUID från fds-df:

# Ett personnummer kan äga flera 
# fastigheter (UUID).

# Därför sparas varje personnummers fastigheter
# i en tuple: ([list of uuids], [len of uuids])

def get_uuid_from_persnr(persnr):
    
    member_mask = fds_df['Intressentkategori'] == 'Medlem'
    persnr_mask = fds_df['Intressentnummer'] == persnr
    
    members = fds_df[member_mask]
    
    uuid = members[persnr_mask]['UUID-Fastighet']
     
    list_of_uuids = []
    
    for i in uuid:
        list_of_uuids.append(i)
        
    return list_of_uuids, len(uuid)

In [25]:
# Skicka in en lista med personnummer (string)
# för att få ut leverantörsnumret.
# En person kan ha flera fastigheter/lev.nr.:

def get_levnr_from_persnr(persnr):
    
    if type(persnr) == list:
    
        lev_nr = []
    
        for k in persnr:
            
            levnr = sir_df[sir_df['personnummer'] == str(k)]['skogsleverantörsnummer']
            lev_nr.append(levnr)
            
    else:
        
        if persnr in sir_df['personnummer'].values:
            lev_nr = sir_df[sir_df['personnummer'] == persnr]['skogsleverantörsnummer']
            
        else:
            lev_nr = []
        
    return lev_nr

In [27]:
# Hämta timmer- och massavedsvolymer för
# ett leverantörsnummer:

def get_volumes(levnr):
    timber_volume = []
    pulp_volume = []
    
    for i in levnr:
        i = int(i)
        
        timber_vol = stubin_df[stubin_df['Levnr'] == i]['Timmer']
        pulp_vol = stubin_df[stubin_df['Levnr'] == i]['Massaved']
        
        timber_volume = float(timber_vol)
        pulp_volume = float(pulp_vol)
        
    return timber_volume, pulp_volume

In [28]:
# Returnerar arean i hektar:

def get_sks_area(uuid):
    avv_areal = float(sks_df[sks_df['UUID'] == uuid]['AVV_AREAL'])
    return avv_areal/10000

In [29]:
volume_per_hectar = 258 # https://www.skogen.se/nyheter/1630-kubikmeter-per-hektar

def calc_volume_from_area(area):
    return volume_per_hectar * area

## Testa flödet med en UUID...

In [79]:
# Välj något random tal...

uuid = '909a6a51-ee98-90ec-e040-ed8f66444c3f'
#uuid = fds_df['UUID-Fastighet'][9823]

In [80]:
# Koppla rätt personnummer från UUID:

personnummer = get_persnr_from_uuid(uuid)
print(personnummer)

['195809283574']

In [81]:
# Hitta rätt levnr från personnummer:

levnr = get_levnr_from_persnr(personnummer)
print(int(levnr[0]))

112780

In [83]:
# Få ut volymerna från ett givet lev.nr.
# Formatet på get_volumes är (timmer, massaved):

volumes = get_volumes(levnr)
print(volumes)

(165.46, 235.59)

In [84]:
# Varför kan jag konvertera volumes här till en numpy-array
# men inte på jobbdatorn? Olika version av numpy...?

np_vol = np.array(volumes)
print(np_vol)

[165.46 235.59]

In [85]:
# Hämta arean från Metrias material för ett UUID.
# Enheten i Metrias material är i m^2, men
# funktionen räknar om det till hektar:

sks_area = get_sks_area(uuid)
print(f'Arean är = {sks_area:.2f} hektar.')

Arean är = 21.86 hektar.

In [36]:
# Uppskattar volymen slutavverkning från en viss area
# från ett visst UUID:

est_vol = calc_volume_from_area(get_sks_area(uuid))

print(f'Estimerad avverkningsvolym = {est_vol:.2f} m3fub.')

Estimerad avverkningsvolym = 5639.19 m3fub.

In [37]:
# Hur kan vi "baklänges" leta reda på denna volym
# inom ett säkerhetsspann (+-10 % ?) i Stubin-datat?

# 2. jämför dessa volymer med den framräknade ovan

In [38]:
# 1. summera volymerna från get_volumes(levnr)

total_stubin_volumes = np.sum(volumes)
print(f'Totala volymen från Stubin är {total_stubin_volumes:,} m3fub.')

Totala volymen från Stubin är 401.05 m3fub.

In [39]:
# I verkligheten tog jag bort alla avverkningsdatum
# förutom ett i Metria-filen, vilket gör att arean 
# ovan är mycket större och kommer därför inte att
# stämma med Stubin-siffrorna.

In [40]:
# En hjälpfunktion för att se om två tal är
# ungefär lika stora. "uncert" är en relativ
# tolerans, t.ex. 0.2 som det får skilja på:

def compare_volumes(estvol, truevol, uncert):
    
    return np.isclose(estvol, truevol, rtol = uncert)

In [86]:
# Jämför volymerna som uppskattats från avverkad area
# och de som är rapporterade i Stubin.
# Om de är "lika" så returneras True och omvänt.

compare_volumes(est_vol, total_stubin_volumes, 0.2)

False

In [42]:
def loyal_member(estvol, truevol, uncert):
    if compare_volumes(estvol, truevol, uncert):
        return True
    else:
        return False

In [87]:
# Är en medlem lojal som levererat 11 m3fub 
# i Stubin och som Skogsstyrelsen uppskattat
# volymen till 10 m3fub?

loyal_member(10, 11, 0.2)

True

In [44]:
# Med givna volymer är medlemmen ovan inte att
# anses som lojal:

loyal_member(est_vol, total_stubin_volumes, 0.3)

False

In [45]:
# För varje medlem så gör vi en ny datafram-column 
# dit vi kan skriva loyal_member.
# Utgå ifrån SIR-df?

## Generell lösning

In [48]:
# För varje medlem vill vi utifrån dennes
# personnummer hämta ett levernatörsnummer
# så att vi kan hämta inmätta volymer i Stubin.
# Utifrån detta vill vi sedan jämföra det mot
# uppskattat volym från en angiven area i 
# Skogsstyrelsens material.

'''
medlems-df = skapa en ny df från FDS-df som bara innehåller personnummer och uuid.

för varje personnummer i medlems-df:
    returnera ett UUID från fds-df # ny funktion (- nyss skapad...)
        m.h.a. uuid hämta en given areal per datum och skriv ner datum och areal # funktion finns!
        
        # Blir varje rad en medlem och varje kolumn ett datum?
        # Men hur skiljer vi då ut massa- och timmervolymerna från varandra?
        # Genom att varje datum förekommer två gånger, ett för respektive sortiment?
    
    returnera motsvarande levnr # funktion finns!
   
    för varje returnerat levnr:
        returnera timmer- och massavolymer från stubin-df # funktion finns!
        skriv ner volymerna i två nya pandas-kolumner i sir-df med rätt kolumn-namn # ny funktion!
    
'''

'\nmedlems-df = skapa en ny df från FDS-df som bara innehåller personnummer och uuid.\n\nför varje personnummer i medlems-df:\n    returnera ett UUID från fds-df # ny funktion (- nyss skapad...)\n        m.h.a. uuid hämta en given areal per datum och skriv ner datum och areal # funktion finns!\n        \n        # Blir varje rad en medlem och varje kolumn ett datum?\n        # Men hur skiljer vi då ut massa- och timmervolymerna från varandra?\n        # Genom att varje datum förekommer två gånger, ett för respektive sortiment?\n    \n    returnera motsvarande levnr # funktion finns!\n   \n    för varje returnerat levnr:\n        returnera timmer- och massavolymer från stubin-df # funktion finns!\n        skriv ner volymerna i två nya pandas-kolumner i sir-df med rätt kolumn-namn # ny funktion!\n    \n'

In [52]:
# Skapa en ny df från ovanstående med 
# två fält, uuid och personnummer:

member_mask = fds_df['Intressentkategori'] == 'Medlem'
members = fds_df[member_mask]

members_df = members[['UUID-Fastighet', 'Intressentnummer']]

In [53]:
members_df.rename(columns={"UUID-Fastighet": "uuid", "Intressentnummer": "intressent_nr"}, inplace = True)

C:\ProgramData\Anaconda3\envs\ml_general\lib\site-packages\pandas\core\frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

In [54]:
members_df.head()

                                    uuid intressent_nr
2   909a6a54-77cb-90ec-e040-ed8f66444c3f  196602252931
12  909a6a51-d272-90ec-e040-ed8f66444c3f  197910161913
17  909a6a5e-facd-90ec-e040-ed8f66444c3f    5564346137
18  7c8ecf36-6ffc-485e-9cb8-4730b26d2948  194608062651
19  909a6a57-650e-90ec-e040-ed8f66444c3f  197805123317

In [55]:
# members_df['intressent_nr'] = members_df['intressent_nr'].astype(int)

In [56]:
# Välj ett personnummer ur ovan:

persnr_member_test = members_df['intressent_nr'].iloc[0]
print(persnr_member_test, type(persnr_member_test))

196602252931 <class 'str'>

In [57]:
# Ta reda på associerade uuid till ovan personnummer:

uuid = get_uuid_from_persnr(persnr_member_test)

print(uuid, type(uuid))

(['909a6a54-77cb-90ec-e040-ed8f66444c3f', '909a6a54-77d9-90ec-e040-ed8f66444c3f', '909a6a55-cc30-90ec-e040-ed8f66444c3f'], 3) <class 'tuple'>

C:\ProgramData\Anaconda3\envs\ml_general\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [604]:
# Kör ej denna - tar lång tid!
# Resultatet av den finns sparad i en pandas-df.

counter = 0
lev_nrs = []

start_time = time.time()

for key, value in members_df['intressent_nr'].iteritems(): 
    #print(value, type(value))
    levnr = get_levnr_from_persnr(value)
    for k in levnr:
        lev_nrs.append(k)
    #print(value, levnr)
    #lev_nrs.append(levnr)
    counter += 1
    
    #if counter == 100:
    #    break
    
end_time = time.time()

delta_time = end_time - start_time

print(f'Det tog {delta_time:.2f} sekunder att loopa igenom allt.')

In [63]:
# Spara listan ovan som en csv-fil m.h.a. Pandas:

generated_lev_nr = pd.DataFrame(lev_nrs, columns=['levnr'] )
generated_lev_nr.to_csv('generated_lev_nr.csv') # spara ner kolumn-namn här?

NameError: name 'lev_nrs' is not defined

In [64]:
generated_lev_nr = pd.read_csv('generated_lev_nr.csv')

In [65]:
generated_lev_nr.shape

(104407, 2)

In [ ]:
# För de personnummer som genererar fler än ett levnr...? 
# Hur hanterar vi det i vår members_df ovan? Som en lista?

# UUID <-> Personnummer <-> Levnr ej unik!
# 1. Försöka få uuid som unik nyckel i alla exporter?
# 2. Avgränsning: bara ha med de medlemmar som är ägare till en fastighet?

In [503]:
# get_levnr_from_persnr(194801233554)

# Denna blir fel då personnumret finns flera gånger
# i sir_df med olika levnr...
# I sir finns den två gånger
# 531499, 301957

sir_df[sir_df['personnummer'] == '194801233554']['skogsleverantörsnummer']

46870    301957
63000    531499
Name: skogsleverantörsnummer, dtype: int64

In [505]:
# I CE finns den med fyra gånger...

members_df[members_df['intressent_nr'] == '194801233554']['uuid']

36        909a6a5f-ea39-90ec-e040-ed8f66444c3f
164367    909a6a5f-ea3a-90ec-e040-ed8f66444c3f
198370    909a6a5f-e20f-90ec-e040-ed8f66444c3f
213842    909a6a5f-d4da-90ec-e040-ed8f66444c3f
Name: uuid, dtype: object